image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - build images
  - test images
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  TEST_IMAGE: registry.gitlab.com/mog33/docker-images
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE: index.docker.io/$RELEASE_USER

################################################################################
# Templates to avoid repeat. A bit Xtrem here!
# https://docs.gitlab.com/ee/ci/yaml/#anchors
################################################################################

.docker_login_gitlab:
  - &docker_login_gitlab docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

.docker_build_push:
  script: &docker_build_push
    - docker build --pull --tag $TEST_IMAGE/$IMAGE $DIR
    - docker push $TEST_IMAGE/$IMAGE

.build_push: &build_push
  stage: build
  script: *docker_build_push

.docker_pull:
  - &docker_pull docker pull $TEST_IMAGE/$IMAGE

.test_base: &test_base
  stage: test
  before_script:
    - *docker_login_gitlab
    - *docker_pull
  script:
    - docker run $TEST_IMAGE/$IMAGE
      sh -c 'useradd -U test && /scripts/change_uid_gid.sh test:test 1001:1001'

.make_build:
  - &make_build apk --no-cache add make gettext && make build

.build_image: &build_image
  stage: build images
  before_script:
    - *docker_login_gitlab
    - *make_build
    - sed -i 's#FROM ${RELEASE_USER}#FROM ${TEST_IMAGE}#g' ${DIR}/Dockerfile
  script: *docker_build_push

.test_images: &test_images
  stage: test images
  before_script:
    - *docker_login_gitlab
    - *docker_pull
    - docker run -d -t --name test $TEST_IMAGE/$IMAGE

.test_images_php: &test_images_php
  <<: *test_images
  script:
    - docker exec test php -v

.test_apache: &test_apache
  script:
    - docker exec test httpd -t -D DUMP_RUN_CFG

.release: &release
  stage: release
  before_script:
    - docker login -u $RELEASE_USER -p $RELEASE_PASSWORD $RELEASE_REGISTRY
  script:
    - *docker_pull
    - docker tag $TEST_IMAGE/$IMAGE $RELEASE_IMAGE/$IMAGE
    - docker push $RELEASE_IMAGE/$IMAGE
  only:
    - master

################################################################################
# Jobs based on previous templates.
# Only variables need to be changed if needed.
################################################################################

before_script:
  - *docker_login_gitlab
  - *make_build

base:3.7:
  <<: *build_push
  variables:
    IMAGE: alpine-base:3.7
    DIR: alpine-base/3.7

base:3.8:
  <<: *build_push
  variables:
    IMAGE: alpine-base:3.8
    DIR: alpine-base/3.8

test:3.7:
  <<: *test_base
  variables:
    IMAGE: alpine-base:3.7

test:3.8:
  <<: *test_base
  variables:
    IMAGE: alpine-base:3.8

apache:
  <<: *build_image
  variables:
    IMAGE: apache:latest
    DIR: apache

php7.1:
  <<: *build_image
  variables:
    IMAGE: php:7.1
    DIR: php/7.1

php7.2:
  <<: *build_image
  variables:
    IMAGE: php:7.2
    DIR: php/7.2

test:apache:
  <<: *test_images
  <<: *test_apache
  variables:
    IMAGE: apache:latest

test:php7.1:
  <<: *test_images_php
  variables:
    IMAGE: php:7.1

test:php7.2:
  <<: *test_images_php
  variables:
    IMAGE: php:7.2

release:base:3.7:
  <<: *release
  variables:
    IMAGE: alpine-base:3.7

release:base:3.8:
  <<: *release
  variables:
    IMAGE: alpine-base:3.8

release:apache:
  <<: *release
  variables:
    IMAGE: apache:latest

release:php:7.1:
  <<: *release
  variables:
    IMAGE: php:7.1

release:php:7.2:
  <<: *release
  variables:
    IMAGE: php:7.2
